### PR TITLE
Add entrypoint for CommonJS

### PR DESCRIPTION
**Pull request by divmain**
This allows tools like Browserify and Webpack to require Handlebones as `handlebones` instead of `handlebones/handlebones`.

### CODE REVIEW

**Comment by mulderp** [comment]
For using browserify, I made a small yeoman generator here: https://www.npmjs.org/package/generator-backbone-browserify

Might be interesting to setup a small example that shows handlebones with browserify. @divmain let me know if we could discuss this idea.

**Comment by mulderp** [comment]
Hmm.. when trying to browserify the packages and using the view helper, I get a:

```
Uncaught Error: Missing helper: 'view' 
```

Seems that the view helpers are not properly setup yet.

**Comment by divmain** [comment]
@mulderp are you using `browserify-handlebars`?  If so, the view helper is not registered during the transform.  I'm looking for a good approach to solve this.

**Comment by mulderp** [comment]
I am looking at hbsfy  - right now, I am looking in a "simplified" setup to understand better the dependency chain. But indeed, the "main" reference in package.json is an important one.

**Comment by divmain** [comment]
Got it.  The problem is that the view helper is registered in the application code, which isn't touched until after the templates are compiled by hbsfy, browserify-handlebars, or any other transform/loader.  I'm looking at the docs for hbsfy now - they provide a mechanism to register custom helpers at compile time.

Definitely open to connecting with you regarding putting together a minimal handlebones generator or example project.

**Comment by divmain** [comment]
Could you add the following to the top of your `main.js`?

``` javascript
var Handlebars = require("hbsfy/runtime");
Handlebars.registerHelper("view", function (view) {
    if (!view) {
      return "";
    }
    var htmlAttributes = {
      // ensure generated placeholder tag in template
      // will match tag of view instance
      tagName: view.el.tagName.toLowerCase()
    };
    htmlAttributes[viewPlaceholderAttributeName] = view.cid;
    var output = Handlebones.Util.tag(htmlAttributes, "", this);
    return new Handlebars.SafeString(output);
  });
```

If it works, we can make a change to expose the helper function like so.

``` javascript
var Handlebars = require("hbsfy/runtime");
Handlebars.registerHelper("view", Handlebones.viewHelper);
```

**Comment by mulderp** [comment]
I pushed a small sandbox here: https://github.com/mulderp/handlebones-playground

You can run `make` and `node server` - not sure where it breaks. Will need to continue later.

**Comment by mulderp** [comment]
Ok, I figured it out: Nested views must be attached with `addChild`  and the `render()` function comes from Handlebones. Good work! Will be interesting to explore this further with CommonJS.

**Comment by mulderp** [comment]
Just wanted to ping on this one.
I am having a talk at http://2014.frontendconf.ch/en/ and could push handelbones a bit as a minimalistic setup with CommonJS

**Comment by divmain** [comment]
Hey @mulderp!  Thanks for the ping.  Merging.

**Pull request merged**
